export const webDevPlans = [
  {
    id: 1,
    title: "START-UP WEBSITE PACKAGE",
    discountedPrice: "$199.00",
    originalPrice: "$650.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "3 Page Website",
      "UI/UX Design",
      "Contact/Query Form",
      "1 Banner Design",
      "2 Stock Photos",
      "Free Favicon Design",
      "Cross Browser Compatible",
      "Complete W3C Certified HTML",
      "Website Initial Concepts in 48 Hours",
      "Complete Design & Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "Value Added Services",
      "Mobile Responsive will be Additional $200*",
      "CMS will be Additional $250*",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    id: 2,
    title: "PROFESSIONAL WEBSITE PACKAGE",
    discountedPrice: "$499.00",
    originalPrice: "$999.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "5 Unique Pages Website",
      "CMS / Admin Panel Support",
      "8 Stock images",
      "6 Banner Designs",
      "1 jQuery Slider Banner",
      "FREE Google Frien,dly Sitemap",
      "Complete W3C CertifiedHTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "Money Back Guarantee",
    ],
  },
  {
    id: 3,
    title: "BUSINESS PRO WEBSITE PACKAGE",
    discountedPrice: "$749.00",
    originalPrice: "$1498.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "8-10 Pages Website",
      "Conceptual and Dynamic Website",
      "Online Payment Integration",
      "Online Booking Tool",
      "Content Management System",
      "Mobile Responsive Website",
      "Custom Forms",
      "Lead Capturing Forms",
      "Striking Hover Effects",
      "Newsletter Subscription",
      "Newsfeed Integration",
      "Social Media Integration",
      "Search Engine Submission",
      "5 Stock Photos",
      "3 Unique Banner Design",
      "JQuery Slider Banner",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Complete Deployment",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 4,
    title: "IDENTITY WEBSITE PACKAGE",
    discountedPrice: "$1599.00",
    originalPrice: "$3199.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "10 Unique Pages Website Design",
      "Custom, Interactive, Dynamic & High End Design",
      "Customize Word Pross (or) PHP Development",
      "Interactive Sliding Banners",
      "10 Stock Images",
      "10 Banner Designs",
      "Special Hover Effects",
      "Unlimited Revisions",
      "Content Management System (WordPress or Custom)",
      "Mobile Responsive",
      "10 Professional Email ID's",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete WBC Certified HTML",
      "Industry specified Team of Award Winning Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    id: 5,
    title: "CORPORATE WEBSITE PACKAGE",
    discountedPrice: "$2599.0000",
    originalPrice: "$5199.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Unlimited Pages Website Design",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Customize WordPress (or) PHP Development",
      "Interactive Sliding Banners",
      "Up to 15 Custom Made Banner Designs",
      "10 Stock Images",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content Management System",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Live Feeds of Social Networks integration (Optional)",
      "Search Bar",
      "Mobile Responsive",
      "Up to 15 Professional Email ID's",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete WBC Certified HTML",
      "Industry specified Team of Award Winning Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
];

export const brandingPlans = [
  {
    id: 1,
    title: "STARTUP COLLATERAL PACKAGE",
    discountedPrice: "$49.00",
    originalPrice: "$99.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "2 Stationery Design Set",
      "FREE Fax Template",
      "Print Ready Formats",
      "UNLIMITED Revisions",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 2,
    title: "COLLATERAL CLASSIC PACKAGE",
    discountedPrice: "$129.00",
    originalPrice: "$259.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "2 Stationery Design Set",
      "UNLIMITED Revisions",
      "Flyer Design",
      "Brochure Design (Bi-fold/Tri-fold)",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 3,
    title: "PREMIUM CLASSIC PACKAGE",
    discountedPrice: "$199.00",
    originalPrice: "$399.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "2 Stationery Design Set",
      "Packaging Design",
      "UNLIMITED Revisions",
      "T-shirt Design",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 4,
    title: "UNLIMITED CLASSIC PACKAGE",
    discountedPrice: "$249.00",
    originalPrice: "$499.99",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "2 Stationery Design Set",
      "Menu Card Design",
      "T-shirt Design",
      "1 Banner Design",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
];

export const videoPlans = [
  {
    id: 1,
    title: "Video Teaser",
    discountedPrice: "$249.00",
    originalPrice: "",
    addOn: "Teaser for initial stage of business",
    features: [
      "30sec Duration",
      "Script Writing",
      "Custom Artwork",
      "Background Music",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
  {
    id: 2,
    title: "Video Startup",
    discountedPrice: "$399.00",
    originalPrice: "",
    addOn: "Suitable for start ups & new business",
    features: [
      "30sec Duration",
      "Script Writing",
      "Professional Voice-over & SFX",
      "Hand-drawn Illustrations",
      "Unlimited Revisions",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
  {
    id: 3,
    title: "Classic Video",
    discountedPrice: "$499.00",
    originalPrice: "",
    addOn: "Ideal for established businesses",
    features: [
      "30sec Duration",
      "Script Writing",
      "Professional Voice-over & SFX",
      "Custom 2D Characters",
      "Unlimited Revisions",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
  {
    id: 4,
    title: "3D Video",
    discountedPrice: "$1999.00",
    originalPrice: "",
    addOn: "Enter the world of 3D animations & CGI",
    features: [
      "2 3D Object Models",
      "Unlimited Storyboard Revisions",
      "Professional Voice – Over",
      "Background Music",
      "Exotic Animations",
      "HD Video Format",
      "6 Weeks Delivery Time",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
];

export const ecommercePlans = [
  {
    id: 1,
    title: "E-COMMERCE WEBSITE PACKAGE",
    discountedPrice: "$1199.00",
    originalPrice: "$2398.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Upto 15 Unique Pages Website",
      "Conceptual and Dynamic Website",
      "Content Management System (CMS)",
      "Mobile Responsive",
      "Easy Product Search",
      "Product Reviews",
      "Up To 100 Products",
      "Unlimited Categories",
      "Shopping Cart Integration",
      "Payment Integration",
      "Sales & Inventory Management",
      "Jquery Slider",
      "Free Google Friendly Sitemap",
      "Custom Email Addresses",
      "Complete WBC Certified HTML",
      "Social Media Designs",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 2,
    title: "CORPORATE E-COMMERCE PACKAGE",
    discountedPrice: "$1949.99",
    originalPrice: "$3599.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Unlimited Unique Pages Website",
      "Conceptual and Dynamic Website",
      "Content Management System (CMS)",
      "Mobile Responsive",
      "Easy Product Search",
      "Product Reviews",
      "Unlimited Products",
      "Unlimited Categories",
      "Customer Login and Personalized",
      "Profiles",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Sales & Inventory Management",
      "Jquery Slider",
      "Free Google Friendly Sitemap",
      "Custom Email Addresses",
      "Complete WBC Certified HTML",
      "Facebook Page Designs",
      "Instagram Page Designs",
      "Twitter Page Designs",
      "Youtube Page Designs",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 3,
    title: "ELITE E-COMMERCE PACKAGE",
    discountedPrice: "$3694.99",
    originalPrice: "$7388.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "UNLIMITED Logo Design Concepts",
      "By 6 Award Winning Designers loon Design",
      "UNLIMITED Revisions",
      "Print Media",
      "Stationary Design (Business Card Letterhead & Envelope)",
      "Invoice Design, Email Signature",
      "Bi-Fold Brochure (OR) 2 Sided Flyer Design",
      "Product Catalog Design",
      "Sign age Design (OR, Label Design",
      "T-Shirt Design (OR) Car Wrap design",
      "Website",
      "E-Commerce Store Design",
      "Product Detail Page Resign",
      "Unique Banner Slider",
      "Featured Products Showecase",
      "Full Shopping Cart Integration",
      "Unlimited Products",
      "Unlimited Categories",
      "Product Rating & Reviews",
      "Easy Product Search",
      "Payment Gateway Integration",
      "Multi-currency Support",
      "Content Management System",
      "Customer Log-in Area",
      "Mobile Responsive",
      "Social Media Plugins Integration",
      "Tell a Friend Feature",
      "Social Media Pages",
      "Facebook, Twitter, YouTube, Google+ & Pinterest Page designs",
      "Value Added Services",
      "Dedicated Accounts Manager",
      "Unlimited Revisions",
      "All Final File Formats",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
];

export const shopifyPlans = [
  {
    id: 1,
    title: "SHOPIFY BASIC PACKAGE",
    discountedPrice: "$749.00",
    originalPrice: "$1649.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Customized Design",
      "Upto 100 Products",
      "Content Management System (CMS)",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Easy Product Search",
      "Dedicated designer & developer",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 2,
    title: "SHOPIFY PLUS PACKAGE",
    discountedPrice: "$1249.00",
    originalPrice: "$2799.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Customized Design",
      "Upto 500 Products",
      "Content Management System (CMS)",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Easy Product Search",
      "Product Reviews",
      "5 Promotional Banners",
      "Team of Expert Designers & Developers",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 3,
    title: "SHOPIFY PRIME PACKAGE",
    discountedPrice: "$1999.00",
    originalPrice: "$7399.00",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Unlimited Pages Website with Unique Design",
      "5 Custom Logo Design",
      "CMS / Backend Administrative System",
      "Unlimited Products with Unlimited Categories",
      "FREE Unlimited Revisions",
      "Custom Shopping Cart Integration",
      "Multiple Payment Module Integration",
      "Multiple Shipping Module Integration",
      "Product Ratings & Reviews",
      "Sales & Inventory Management System",
      "Multiple Currency Support",
      "Customer Login Area (Sign-Up & Sign-in)",
      "Mobile Responsive",
      "Social Media Designs (Facebook, Twitter, YouTube)",
      "Dedicated Team of Expert Designers & Developers",
      "Dedicated Project Manager",
      "Newsletter Subscription",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
];

export const seoPlans = [
  {
    id: 1,
    title: "SEO BASIC PACKAGE",
    discountedPrice: "$1499.99",
    originalPrice: "",
    addOn: "$950 - Quarterly Plan $300 - Recurring Monthly Payment",
    features: [
      "Campaign Setup And Optimization",
      "Prior Analysis",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "15 Selected Keywords Targeting",
      "15 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Tracking & Analysis",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ's",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
    ],
  },
  {
    id: 2,
    title: "PREMIUM SEO PACKAGE",
    discountedPrice: "$1999.99",
    originalPrice: "",
    addOn: "$1600 - Quarterly Plan $450 - Recurring Monthly Payment",
    features: [
      "Prior Analysis",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "30 Selected Keywords Targeting",
      "30 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of huskys tags",
      "inclusion of huskys Indexing",
      "Modifications",
      "Tracking & Analysis",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ's",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
    ],
  },
  {
    id: 3,
    title: "PLATINIUM SEO PACKAGE",
    discountedPrice: "$2499.99",
    originalPrice: "",
    addOn: "$1600 - Quarterly Plan $700 - Recurring Monthly Payment",
    features: [
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "70 Selected Keywords Targeting",
      "50 Pages Keyword Targeted",
      "Webpage Optimization",
      "Meta Tags Creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of huskys tags",
      "inclusion of huskys Indexing",
      "Modifications",
      "Tracking & Analysis",
      "Tracking & Analysis",
      "Google Places Inclusions",
      "Google Analytics Installation",
      "Google Webmaster Installation",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ's",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
      "Blog Content Creation",
      "Local SEO",
    ],
  },
]

export const logoPlans = [
  {
    id: 1,
    title: "BASIC LOGO PACKAGE",
    discountedPrice: "$45.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "4 Custom Logo Design Concepts",
      "By 2 Designers",
      "4 Revisions",
      "24 Hours TAT",
      "100% Unique Design Guarantee",
    ],
  },
  {
    id: 2,
    title: "STARTUP LOGO PACKAGE",
    discountedPrice: "$95.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "8 Custom Logo Design Concepts",
      "By 4 Designers",
      "24 Hours TAT",
      "100% Unique Design Guarantee",
    ],
  },
  {
    id: 3,
    title: "PROFESSIONAL LOGO PACKAGE",
    discountedPrice: "$125.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Multiple Logo Design Concepts",
      "By 5 Designers",
      "FREE Stationary Design Sets",
      "FREE MS Word Letterhead",
      "48 to 72 Hours TAT",
      "100% Unique Design Guarantee",
    ],
  },
  {
    id: 4,
    title: "ELITE LOGO PACKAGE",
    discountedPrice: "$175.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Multiple Logo Design Concepts",
      "By 5 Designers",
      "FREE Stationary Design Sets",
      "FREE Email Signature",
      "All Final Files Format (Al, PSD, EPS, PNG, GIF, JPF, PDF)",
      "100% Unique Design Guarantee",
      "48 to 72 hours TAT",
    ],
  },
  {
    id: 5,
    title: "MASCOT LOGO PACKAGE",
    discountedPrice: "$250.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Multiple Logo Design Concepts",
      "By 8 Designers",
      "2 Stationary Design Sets",
      "Double Sided Flyer Design",
      "Bi-Fold Brochure",
      "FREE MS Word Letterhead",
      "FREE Email Signature",
      "Social Media Banner Designs",
      "All Final Files Format (Al, PSD, EPS, PNG, GIF, JPF, PDF)",
      "100% Unique Design Guarantee",
    ],
  },
]

export const socialPlans = [
  {
    id: 1,
    title: "Bronze Monthly",
    discountedPrice: "$199.00",
    originalPrice: "",
    addOn: "Suitable for newly formed organizations or small start ups.",
    features: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "3 Posts per Week",
      "1 Facebook Event",
      "Monthly Reporting",
      "Ad spend – Up to $50",
    ],
  },
  {
    id: 2,
    title: "Silver Monthly",
    discountedPrice: "$299.00",
    originalPrice: "",
    addOn: "Enhanced your social media game with this medium ranged package",
    features: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "4 Posts per Week",
      "2 Facebook Events",
      "Monthly Reporting",
      "Ad Spend – Up to $65",
    ],
  },
  {
    id: 3,
    title: "Gold Monthly",
    discountedPrice: "$499.00",
    originalPrice: "",
    addOn: "Social media solutions for well established businesses",
    features: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "5 Posts per Week",
      "2 Facebook Events",
      "1 Lead Generation Campaign",
      "Monthly Reporting",
      "Ad Spend – Up to $120",
    ],
  },
  {
    id: 4,
    title: "Platinum Monthly",
    discountedPrice: "$749.00",
    originalPrice: "",
    addOn: "Social media marketing for big companies and businesses",
    features: [
      "Optimize FB Page",
      "1 Social Cover + Holiday Covers",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "6 Posts per Week",
      "2 Facebook Events",
      "1 Lead Generation Campaign",
      "Monthly Reporting",
      "Ad Spend – Up to $170",
    ],
  },
]