export const webDevPlans = [
  // {
  //   id: 1,
  //   title: "START-UP WEBSITE PACKAGE",
  //   discountedPrice: "$199.00",
  //   originalPrice: "$650.00",
  //   addOn: "Add on: $199 for 30-second Explainer Video Animation",
  //   features: [
  //     "3 Page Website",
  //     "UI/UX Design",
  //     "Contact/Query Form",
  //     "1 Banner Design",
  //     "2 Stock Photos",
  //     "Free Favicon Design",
  //     "Cross Browser Compatible",
  //     "Complete W3C Certified HTML",
  //     "Website Initial Concepts in 48 Hours",
  //     "Complete Design & Deployment",
  //     "Complete Source Files",
  //     "Dedicated Project Manager",
  //     "100% Ownership Rights",
  //     "100% Satisfaction Guarantee",
  //     "100% Money Back Guarantee",
  //     "Value Added Services",
  //     "Mobile Responsive will be Additional $200*",
  //     "CMS will be Additional $250*",
  //     "*NO MONTHLY OR ANY HIDDEN FEE*",
  //   ],
  // },
  {
    id: 2,
    title: "BASIC WEBSITE PACKAGE",
    discountedPrice: "$699",
    originalPrice: "$999.00",
    inclusion: "What's Included:",
    addOn:
      "Ideal for small businesses or startups needing a quick, professional online presence",
    features: [
      "5 Unique Website Pages",
      "CMS / Admin Panel Integration",
      "8 High-Quality Stock Images",
      "6 Custom Banner Designs",
      "1 jQuery Slider Banner",
      "Free Google-Friendly XML Sitemap",
      "Fully W3C-Compliant HTML Code",
      "Fast Turnaround (48 to 72 Hours)",
      "Social Media Branding:",
      "Facebook Business Page",
      "Twitter Profile Design",
      "YouTube Channel Branding",
      "Complete Website Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Custom Design Guarantee",
      "Money-Back Guarantee",
      "No Monthly Fees or Hidden Charges",
    ],
  },
  // {
  //   id: 3,
  //   title: "BUSINESS PRO WEBSITE PACKAGE",
  //   discountedPrice: "$749.00",
  //   originalPrice: "$1498.00",
  //   addOn: "Add on: $199 for 30-second Explainer Video Animation",
  //   features: [
  //     "8-10 Pages Website",
  //     "Conceptual and Dynamic Website",
  //     "Online Payment Integration",
  //     "Online Booking Tool",
  //     "Content Management System",
  //     "Mobile Responsive Website",
  //     "Custom Forms",
  //     "Lead Capturing Forms",
  //     "Striking Hover Effects",
  //     "Newsletter Subscription",
  //     "Newsfeed Integration",
  //     "Social Media Integration",
  //     "Search Engine Submission",
  //     "5 Stock Photos",
  //     "3 Unique Banner Design",
  //     "JQuery Slider Banner",
  //     "Complete W3C Certified HTML",
  //     "48 to 72 hours TAT",
  //     "Facebook Page Design",
  //     "Twitter Page Design",
  //     "YouTube Page Design",
  //     "Complete Deployment",
  //     "100% Unique Design Guarantee",
  //     "100% Money Back Guarantee",
  //   ],
  // },
  {
    id: 4,
    title: "STANDARD WEBSITE PACKAGE",
    discountedPrice: "$1599.00",
    originalPrice: "$3199.00",
    inclusion: "Includes everything in Basic, plus:",
    addOn:
      "Perfect for established businesses wanting custom, interactive websites",
    features: [
      "10 Unique Pages Website Design",
      "Custom, Interactive, Dynamic & High End Design",
      "Customize Word Pross (or) PHP Development",
      "Interactive Sliding Banners",
      "10 Stock Images",
      "10 Banner Designs",
      "Special Hover Effects",
      "Unlimited Revisions",
      "Content Management System (WordPress or Custom)",
      "Mobile Responsive",
      "10 Professional Email ID's",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete WBC Certified HTML",
      "Industry specified Team of Award Winning Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
      "*NO MONTHLY OR ANY HIDDEN FEE*",
    ],
  },
  {
    id: 5,
    title: "PREMIUM WEBSITE PACKAGE",
    discountedPrice: "$2,699",
    originalPrice: "$5,199.00",
    inclusion: "Includes everything in Standard, plus:",
    addOn:
      "Best suited for enterprises or advanced projects needing a custom, feature-rich site",
    features: [
      "Unlimited Pages Website Design",
      "Up to 15 Custom Banner Designs",
      "10 High-Resolution Stock Images",
      "Enhanced Hover Effects & Animations",
      "Unlimited Revisions",
      "Live Social Media Feeds Integration (Optional)",
      "Built-In Website Search Bar",
      "Newsletter & Offers Signup Area",
      "Custom Dynamic Forms (Optional)",
      "Fully Mobile-Responsive Design",
      "Powerful CMS (WordPress or PHP)",
      "Up to 15 Professional Business Email Accounts",
      "Fully SEO-Optimized & W3C-Compliant HTML Code",
      "Enhanced Visibility through Search Engine Submission",
      "Expert Design & Development by Award-Winning Professionals",
      "End-to-End Support from Dedicated Project Manager",
      "Free Value-Added Services",
      "100% Ownership Rights",
      "100% Unique Design & Satisfaction Guarantee",
      "100% Money-Back Guarantee",
      "No Recurring Charges or Hidden Fees",
    ],
  },
];

export const brandingPlans = [
  // {
  //   id: 1,
  //   title: "STARTUP COLLATERAL PACKAGE",
  //   discountedPrice: "$49.00",
  //   originalPrice: "$99.00",
  //   addOn: "Add on: $199 for 30-second Explainer Video Animation",
  //   features: [
  //     "2 Stationery Design Set",
  //     "FREE Fax Template",
  //     "Print Ready Formats",
  //     "UNLIMITED Revisions",
  //     "100% Satisfaction Guarantee",
  //     "100% Money Back Guarantee",
  //   ],
  // },
  {
    id: 2,
    title: "BASIC DESIGN & BRANDING PACKAGE PLAN",
    discountedPrice: "$249",
    originalPrice: "$499",
    inclusion: "What's Included:",
    addOn: "Ideal for startups and small businesses",
    features: [
      "2 Stationery Design Sets",
      "Business Card Design",
      "Letterhead Design (Print + MS Word)",
      "Envelope Design",
      "Email Signature Design",
      "Invoice Design",
      "Flyer Design",
      "Brochure Design (Bi-Fold or Tri-Fold)",
      "Facebook Banner Design",
      "YouTube Banner Design",
      "Twitter Banner Design",
      "LinkedIn Banner Design",
      "Logo Watermark",
      "4 Custom Logo Design Concepts",
      "Created by 2 Professional Designers",
      "4 Revisions",
      "24-Hour Turnaround Time",
      "100% Unique Design Guarantee",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Money-Back Guarantee",
    ],
  },
  {
    id: 3,
    title: "STANDARD DESIGN & BRANDING PACKAGE PLAN",
    discountedPrice: "$349",
    originalPrice: "$649",
    inclusion: "Includes everything in Basic, plus:",
    addOn: "Perfect for growing brands expanding their visual identity",
    features: [
      "Favicon Design",
      "Packaging Design",
      "Signage Design",
      "T-Shirt / Polo Design",
      "Cap / Hat Design",
      "Bag Design",
      "Multiple Logo Concepts",
      "Designed by 5 Professional Designers",
      "48–72 Hour Turnaround Time",
    ],
  },
  {
    id: 4,
    title: "PREMIUM DESIGN & BRANDING PACKAGE PLAN",
    discountedPrice: "$449",
    originalPrice: "$749",
    inclusion: "Includes everything in Standard, plus:",
    addOn: "Best for businesses needing full-spectrum branding",
    features: [
      "Double-Sided Flyer Design",
      "Bi-Fold Brochure",
      "Menu Card Design",
      "1 Custom Banner Design",
      "Product Mockups",
      "General Social Media Banner Designs",
      "FREE MS Word Letterhead",
      "FREE Email Signature",
      "Designed by 8 Professional Designers",
    ],
  },
];

export const videoPlans = [
  {
    id: 1,
    title: "BASIC VIDEO PACKAGE",
    discountedPrice: "$249.00",
    originalPrice: "",
    addOn: "Teaser for initial stage of business",
    features: [
      "30sec Duration",
      "Script Writing",
      "Custom Artwork",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },

  {
    id: 3,
    title: "STANDARD VIDEO PACKAGE",
    discountedPrice: "$499.00",
    originalPrice: "",
    addOn: "Ideal for established businesses",
    features: [
      "30sec Duration",
      "Script Writing",
      "Professional Voice-over & SFX",
      "Custom 2D Characters",
      "Unlimited Revisions",
      "HD Format Video",
      "Dedicated Support",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
  {
    id: 4,
    title: "PREMIUM VIDEO PACKAGE",
    discountedPrice: "$1999.00",
    originalPrice: "",
    addOn: "Enter the world of 3D animations & CGI",
    features: [
      "2 3D Object Models",
      "Unlimited Storyboard Revisions",
      "Professional Voice – Over",
      "Background Music",
      "Exotic Animations",
      "HD Video Format",
      "6 Weeks Delivery Time",
      "100% Ownership Rights",
      "100% Money-back Guarantee",
    ],
  },
];

export const ecommercePlans = [
  {
    id: 1,
    title: "BASIC E-COMMERCE PACKAGE",
    discountedPrice: "$1199.00",
    originalPrice: "$2,499.00",
    inclusion: "What's Included:",
    addOn: "Perfect for startups and small e-commerce businesses",
    features: [
      "Up to 15 Unique Website Pages",
      "Conceptual, Dynamic, and Custom Design",
      "CMS: WordPress (Woo Commerce) or Shopify",
      "Fully Mobile-Responsive Design",
      "Advanced Product Search Functionality",
      "Customer Reviews & Ratings System",
      "Add up to 100 Products",
      "Unlimited Product Categories & Filters",
      "Integrated Shopping Cart System",
      "Secure Payment Gateway Integration",
      "Complete Sales & Inventory Management System",
      "jQuery Slider for Featured Banners",
      "Free Google-Friendly XML Sitemap",
      "Professional Email Addresses Setup",
      "SEO-Friendly HTML Code (W3C Compliant)",
      "Social Media Profile Design Integration",
      "Complete Website Deployment & Launch",
      "Dedicated Account Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money-Back Guarantee",
    ],
  },
  {
    id: 2,
    title: "STANDARD E-COMMERCE PACKAGE",
    discountedPrice: "$1,949",
    originalPrice: "$3,599",
    inclusion: "Includes everything in Basic, plus:",
    addOn: "Best for growing online stores with larger product lines",
    features: [
      "Unlimited Unique Website Pages",
      "High-End Custom Design",
      "Unlimited Product Upload Capability",
      "Customer Login & Personalized Profiles",
      "Full Shopping Cart & Secure Payment Module",
      "Advanced Sales & Inventory Management",
      "Facebook Business Page Design",
      "Instagram Branding",
      "Twitter & YouTube Channel Design",
      "SEO-Optimized HTML (Fully W3C-Compliant)",
      "Enhanced Visual Highlights with jQuery Slider",
      "Personalized Support from Dedicated Account Manager",
    ],
  },
  {
    id: 3,
    title: "PREMIUM E-COMMERCE PACKAGE",
    discountedPrice: "$3,899",
    originalPrice: "$7,899",
    inclusion: "Includes everything in Standard, plus:",
    addOn: "Ideal for established e-commerce brands & enterprises",
    features: [
      "UNLIMITED Logo Concepts by 6 Award-Winning Designers",
      "Unlimited Revisions on All Designs",
      "Print Media & Stationery Design",
      "Custom Invoice & Email Signature Design",
      "Bi-Fold Brochure or Two-Sided Flyer Design",
      "Product Catalog Design",
      "Signage or Product Label Design",
      "Product Packaging Mockups",
      "Full Custom Website & Store Design (Woo Commerce/Shopify)",
      "Redesign of Product Detail Pages",
      "Unique Banner Slider Design",
      "Featured Products Showcase Section",
      "Unlimited Products & Categories",
      "Multi-Currency Support",
      "Secure Payment Gateway & Advanced Cart Integration",
      "Smart Product Search & Customer Account Management",
      "Fully Responsive Across All Devices",
      "Social Media Plugins Integration",
      "Tell a Friend” Referral System",
      "Social Media Page Designs for:",
      "Facebook, Twitter, YouTube, Google+, Pinterest",
      "All Final File Formats Delivered",
      "Unlimited Revisions Throughout Project",
      "Oversight by Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money-Back Guarantee",
    ],
  },
];

export const shopifyPlans = [
  {
    id: 1,
    title: "BASIC SHOPIFY STORE ACKAGE",
    discountedPrice: "$699",
    originalPrice: "$999",
    inclusion: "What’s Included:",
    addOn: "Perfect for startups and small businesses",
    features: [
      "Customized Design",
      "Up to 100 Products",
      "Content Management System (CMS)",
      "Shopping Cart Integration",
      "Payment Module Integration",
      "Easy Product Search",
      "Dedicated Designer & Developer",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Money-Back Guarantee",
    ],
  },
  {
    id: 2,
    title: "STANDARD SHOPIFY STORE PACKAGE",
    discountedPrice: "$1,299.00",
    originalPrice: "$2,799.00",
    inclusion: "Includes everything in Basic, plus:",
    addOn: "Recommended for growing e-commerce brands",
    features: [
      "Up to 500 Products",
      "Full Shopping Cart Integration",
      "Product Reviews",
      "5 Promotional Banners",
      "Team of Expert Designers & Developers",
      "100% Unique Design Guarantee",
    ],
  },
  {
    id: 3,
    title: "PREMIUM SHOPIFY STORE PACKAGE",
    discountedPrice: "$2,499",
    originalPrice: "$7,399",
    inclusion: "Includes everything in Standard, plus:",
    addOn: "Ideal for enterprise-level stores & large inventories ",
    features: [
      "Unlimited Pages Website with Unique Design",
      "5 Custom Logo Designs",
      "CMS / Backend Administrative System",
      "Unlimited Products with Unlimited Categories",
      "Custom Shopping Cart Integration",
      "Multiple Payment Module Integration",
      "Multiple Shipping Module Integration",
      "Product Ratings & Reviews",
      "Sales & Inventory Management System",
      "Multiple Currency Support",
      "Customer Login Area (Sign-Up & Sign-In)",
      "Fully Mobile-Responsive Design",
      "Social Media Designs (Facebook, Twitter, YouTube)",
      "Dedicated Team of Expert Designers & Developers",
      "Dedicated Project Manager",
      "Newsletter Subscription Integration",
    ],
  },
];

export const seoPlans = [
  {
    id: 1,
    title: "BASIC SEO PACKAGE",
    discountedPrice: "$499 /month",
    originalPrice: "$1,499",
    addOn: "Perfect for new organizations or small startups",
    savings: "(Quarterly: $1,199 – Save $299)",
    inclusion: "What's Included:",
    features: [
      "Campaign Setup and Optimization",
      "Prior Analysis:",
      "\t\tBusiness Analysis",
      "\t\tConsumer Analysis",
      "\t\tCompetitor Analysis",
      "15 Selected Keywords Targeted",
      "15 Pages Optimized",
      "Webpage Optimization:",
      "\t\tMeta Tags Creation",
      "\t\tKeyword Optimization",
      "\t\tImage Optimization",
      "Tracking & Analysis",
      "Google Analytics Installation",
      "Google Search Console Setup",
      "Call-to-Action Plan",
      "Sitemap Creation",
      "Monthly Reporting",
      "Performance Recommendations",
      "Email & Phone Support",
      "Social Bookmarking",
      "SlideShare Marketing",
      "Forums / FAQs Participation",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
    ],
  },
  {
    id: 2,
    title: "STANDARD SEO PACKAGE",
    discountedPrice: "$599 /month",
    originalPrice: "$1,799",
    addOn: "Tailored for well-established businesses",
    savings: "(Quarterly: $1,499.99 – Save $299.98)",
    inclusion: "Includes everything in Basic, plus:",
    features: [
      "30 Selected Keywords Targeted",
      "30 Pages Optimized",
      "Heading Tags Optimization (H1, H2, H3)",
      "Search Engine Indexing Inclusion",
      "On-Page Content Modifications",
      "Google Places Inclusion",
      "Strategic Performance Recommendations",
    ],
  },
  {
    id: 3,
    title: "PREMIUM SEO PACKAGE",
    discountedPrice: "$799 /month",
    originalPrice: "$2,399",
    addOn: "Ideal for enterprises & high-competition industries",
    savings: "(Quarterly: $1,999.99 – Save $399)",
    inclusion: "Includes everything in Standard, plus:",
    features: [
      "70 Selected Keywords Targeted",
      "50 Pages Optimized",
      "Blog Content Creation",
      "Local SEO Implementation",
    ],
  },
];

export const logoPlans = [
  {
    id: 1,
    title: "BASIC LOGO PACKAGE",
    discountedPrice: "$45.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "4 Custom Logo Design Concepts",
      "By 2 Designers",
      "4 Revisions",
      "24 Hours TAT",
      "100% Unique Design Guarantee",
    ],
  },
  // {
  //   id: 3,
  //   title: "PROFESSIONAL LOGO PACKAGE",
  //   discountedPrice: "$125.00",
  //   originalPrice: "",
  //   addOn: "Add on: $199 for 30-second Explainer Video Animation",
  //   features: [
  //     "Multiple Logo Design Concepts",
  //     "By 5 Designers",
  //     "FREE Stationary Design Sets",
  //     "FREE MS Word Letterhead",
  //     "48 to 72 Hours TAT",
  //     "100% Unique Design Guarantee",
  //   ],
  // },
  {
    id: 4,
    title: "STANDARD LOGO PACKAGE",
    discountedPrice: "$175.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Multiple Logo Design Concepts",
      "By 5 Designers",
      "FREE Stationary Design Sets",
      "FREE Email Signature",
      "All Final Files Format (Al, PSD, EPS, PNG, GIF, JPF, PDF)",
      "100% Unique Design Guarantee",
      "48 to 72 hours TAT",
    ],
  },
  {
    id: 5,
    title: "PREMIUM LOGO PACKAGE",
    discountedPrice: "$250.00",
    originalPrice: "",
    addOn: "Add on: $199 for 30-second Explainer Video Animation",
    features: [
      "Multiple Logo Design Concepts",
      "By 8 Designers",
      "2 Stationary Design Sets",
      "Double Sided Flyer Design",
      "Bi-Fold Brochure",
      "FREE MS Word Letterhead",
      "FREE Email Signature",
      "Social Media Banner Designs",
      "All Final Files Format (Al, PSD, EPS, PNG, GIF, JPF, PDF)",
      "100% Unique Design Guarantee",
    ],
  },
];

export const socialPlans = [
  {
    id: 1,
    title: "BASIC SMM PACKAGE",
    discountedPrice: "$549 /month",
    originalPrice: "$1,647",
    inclusion: "What's Included:",
    savings: "(Quarterly: $1399.00 – Save $248.00)",
    addOn: "Perfect for new organizations or small startups",
    features: [
      "Social Channels: Facebook, Instagram",
      "Social Media Audit",
      "Business Analysis",
      "Set Up and Optimization of Business Page/Profile",
      "Page Management",
      "3 Posts per Week",
      "Includes: Single Posts, Reels, Carousels",
      "2 Social Covers",
      "Content Calendar",
      "Content Creation",
      "Hashtag Optimization",
      "Advertisement Campaign Setup",
      "Budget Up to $50 (Ad spend not included)",
      "Monthly Reporting & Goal Evaluation",
      "Dedicated Social Media Manager",
      "100% Satisfaction Guarantee",
      "100% Money-Back Guarantee",
    ],
  },
  // {
  //   id: 2,
  //   title: "Silver Monthly",
  //   discountedPrice: "$299.00",
  //   originalPrice: "",
  //   addOn: "Enhanced your social media game with this medium ranged package",
  //   features: [
  //     "Optimize FB Page",
  //     "1 Social Cover",
  //     "Engagement",
  //     "Reviews",
  //     "Check-ins",
  //     "Posts",
  //     "Shares",
  //     "Mentions",
  //     "Invite to Like",
  //     "Inbox Responses",
  //     "4 Posts per Week",
  //     "2 Facebook Events",
  //     "Monthly Reporting",
  //     "Ad Spend – Up to $65",
  //   ],
  // },
  {
    id: 3,
    title: "STANDARD SMM PACKAGE",
    discountedPrice: "$749 /month",
    originalPrice: "$2,247",
    addOn: "Social media solutions for well-established businesses",
    savings: "(Quarterly: $1,999.00 – Save $248.00)",
    inclusion: "Includes everything in Basic, plus:",
    features: [
      "Social Channels: + Twitter (Total: Facebook, Instagram, Twitter)",
      "3 Social Covers",
      "4 Posts per Week (Single, Reels, Carousels)",
      "Image Alt Text for Accessibility & SEO",
      "Community Management (Comments, DMs, etc.)",
      "Social Media Engagement Campaigns",
      "Increased Ad Budget: Up to $100 (Ad spend not included)",
    ],
  },
  {
    id: 4,
    title: "PREMIUM SMM PACKAGE",
    discountedPrice: "$949 /month",
    originalPrice: "$2,847",
    addOn: "Ideal for enterprises & high-growth brands",
    inclusion: "Includes everything in Standard, plus:",
    savings: "(Quarterly: $2,499.00 – Save $348.00)",
    features: [
      "Social Channels: + LinkedIn, Pinterest (Total: Facebook, Instagram, Twitter, LinkedIn, Pinterest)",
      "5 Social Covers",
      "5 Posts per Week (Single, Reels, Carousels)",
      "Reputation Management (Brand mentions, reviews, alerts)",
      "Ad Budget Up to $200 (Ad spend not included)",
    ],
  },
];

export const googleAdsPlans = [
  {
    id: 1,
    title: "Basic PPC Package",
    discountedPrice: "$999 /month",
    originalPrice: "",
    inclusion: "What's included:",
    addOn: "Ideal for small businesses starting with paid advertising.",
    features: [
      "Google Ads Account Setup",
      "Search Ad Campaign (1 Campaign)",
      "Budget Planning (Ads Payment Not Included) Up to $500 Ad Spend",
      "CPC Optimization",
      "Keyword Research (Up to 10 Keywords)",
      "1 Landing Page Optimization",
      "Ad Extensions Setup (Basic)",
      "Conversion Tracking Setup",
      "1 Account Manager",
      "Monthly Performance Report",
      "1 Strategy Consultation / Month",
      "100% Ownership of Ad Account",
    ],
  },
  // {
  //   id: 2,
  //   title: "Silver Monthly",
  //   discountedPrice: "$299.00",
  //   originalPrice: "",
  //   addOn: "Enhanced your social media game with this medium ranged package",
  //   features: [
  //     "Optimize FB Page",
  //     "1 Social Cover",
  //     "Engagement",
  //     "Reviews",
  //     "Check-ins",
  //     "Posts",
  //     "Shares",
  //     "Mentions",
  //     "Invite to Like",
  //     "Inbox Responses",
  //     "4 Posts per Week",
  //     "2 Facebook Events",
  //     "Monthly Reporting",
  //     "Ad Spend – Up to $65",
  //   ],
  // },
  {
    id: 3,
    title: "Standard PPC Package",
    discountedPrice: "$1599 /month",
    originalPrice: "",
    inclusion: "Includes Everything in Basic, plus:",
    addOn: "Best for growing businesses looking to scale and improve ROI",
    features: [
      "3 Campaigns (Search + Display)",
      "Budget Planning (Ads Payment Not Included) Up to $2,000 Ad Spend",
      "Keyword Research (Up to 30 Keywords)",
      "Retargeting / Remarketing Ads",
      "Custom Landing Page Creation (Up to 2 Pages)",
      "A/B Testing for Ads and Landing Pages",
      "Competitor Ad Analysis",
      "Geo & Device Targeting",
      "Advanced Ad Extensions (Sitelinks, Callouts, etc.)",
      "3 Account Managers",
      "Bi-Weekly Reporting",
      "2 Strategy Consultations / Month",
    ],
  },
  {
    id: 4,
    title: "Premium PPC Package",
    discountedPrice: "$2499 /month",
    originalPrice: "",
    inclusion: "Includes Everything in Standard, plus:",
    addOn: "Built for established businesses that need aggressive PPC growth",
    features: [
      "5+ Campaigns (Search, Display, Retargeting, Shopping if needed)",
      "Unlimited Keyword Research",
      "Budget Planning (Ads Payment Not Included) Custom – No Limit on Ad Spend",
      "Dedicated Conversion-Optimized Landing Page Design",
      "Dynamic Ad Creation & Copywriting",
      "Full Funnel Strategy Setup",
      "Integration with Google Analytics, Tag Manager, and CRM",
      "Heat map & Click Tracking Setup",
      "Weekly Campaign Optimization & Budget Adjustments",
      "5 Dedicated Account Managers",
      "Weekly Reporting + ROI Dashboard Access",
      "Unlimited Strategy Consultations",
    ],
  },
];
export const uiuxPlans = [
  {
    id: 1,
    title: "BASIC UI/UX DESIGN PACKAGE",
    discountedPrice: "$599",
    originalPrice: "",
    inclusion: "What's included:",
    addOn: "Starter Plan for startups and small projects",
    features: [
      "User Research & Requirement Gathering",
      "Basic Wireframes for up to 3 Screens",
      "Simple Interactive Prototypes",
      "UI Style Guide (Fonts, Colors, Buttons)",
      "Responsive Design for Mobile & Desktop",
      "2 Design Revisions",
      "Delivery in Multiple Formats (Sketch, Figma, Adobe XD, PNG)",
      "100% Satisfaction Guarantee",
      "100% Money-Back Guarantee",
    ],
  },
  // {
  //   id: 2,
  //   title: "Silver Monthly",
  //   discountedPrice: "$299.00",
  //   originalPrice: "",
  //   addOn: "Enhanced your social media game with this medium ranged package",
  //   features: [
  //     "Optimize FB Page",
  //     "1 Social Cover",
  //     "Engagement",
  //     "Reviews",
  //     "Check-ins",
  //     "Posts",
  //     "Shares",
  //     "Mentions",
  //     "Invite to Like",
  //     "Inbox Responses",
  //     "4 Posts per Week",
  //     "2 Facebook Events",
  //     "Monthly Reporting",
  //     "Ad Spend – Up to $65",
  //   ],
  // },
  {
    id: 3,
    title: "STANDARD UI/UX DESIGN PACKAGE",
    discountedPrice: "$1,299",
    originalPrice: "",
    inclusion: "Includes Everything in Basic, plus:",
    addOn: "Recommended for growing businesses and mid-sized projects",
    features: [
      "Detailed User Research & Personas",
      "Wireframes for up to 7 Screens",
      "High-Fidelity Interactive Prototypes",
      "UI Style Guide + Design System (Components, Icons)",
      "Responsive Design for Multiple Devices (Mobile, Tablet, Desktop)",
      "Usability Testing & Feedback Integration",
      "4 Design Revisions",
      "Collaboration via Figma/Adobe XD for Real-Time Feedback",
      "Delivery in all Major Formats (Figma, Sketch, Adobe XD, PNG, PDF)",
      "100% Unique Design Guarantee",
      "100% Satisfaction & Money-Back Guarantee",
    ],
  },
  {
    id: 4,
    title: "PREMIUM UI/UX DESIGN PACKAGE",
    discountedPrice: "$2,499",
    originalPrice: "",
    inclusion: "Includes Everything in Standard, plus:",
    addOn: "Ideal for enterprises, apps, and advanced platforms",
    features: [
      "Extensive User Research, Analytics & Competitor Analysis",
      "Wireframes & Prototypes for Unlimited Screens",
      "User Journey Mapping & Flow Diagrams",
      "Comprehensive UI Style Guide & Full Design System",
      "Advanced Interactive Prototypes with Micro-Interactions",
      "Accessibility & Compliance Checks (WCAG)",
      "User Testing with Real Users and Detailed Reports",
      "Up to 8 Design Revisions",
      "Handoff to Developers with Specs & Assets",
      "Post-Launch UX Support & Optimization Suggestions",
      "Dedicated UI/UX Designer & Project Manager",
      "Delivery in all formats including Zeplin, Figma, Adobe XD, PNG, PDF",
      "100% Satisfaction & Money-Back Guarantee",
    ],
  },
];
